# Generated by Django 2.2.3 on 2019-08-03 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0014_auto_20190729_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REJECTED', 'REJECTED'), ('ACCEPTED', 'ACCPETED'), ('UNDECIDED', 'UNDECIDED')], default='UNDECIDED', max_length=20)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Positions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
