# Generated by Django 2.2.3 on 2019-07-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190727_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='past_projects',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Project'),
        ),
    ]
