# Generated by Django 2.2.3 on 2019-07-27 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190727_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='past_projects',
        ),
    ]
