# Generated by Django 2.2.3 on 2019-07-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_past_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='past_projects',
        ),
    ]
