# Generated by Django 2.2.3 on 2019-07-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190728_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
