# Generated by Django 2.2.3 on 2019-08-04 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190804_1844'),
        ('accounts', '0014_auto_20190729_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='project',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyProject',
        ),
        migrations.DeleteModel(
            name='Positions',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
